routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/{slug}/download', 'PluginUpdateController@downloadPlugin');
Route::get('/image/{slug}', 'PluginUpdateController@returnImage');
Route::get('/{slug}/update', 'PluginUpdateController@pluginDetails');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'PluginController@index')->name('home');
    Route::get('/{slug}/versions', 'VersionController@index')->name('versions.index');
    Route::get('/{slug}/versions/create', 'VersionController@create')->name('versions.create');
    Route::post('/{slug}/versions', 'VersionController@store')->name('versions.store');
    Route::get('/{slug}/versions/{version}/edit', 'VersionController@edit')->name('versions.edit');
    Route::put('/{slug}/versions/{version}/store', 'VersionController@update')->name('versions.update');
    Route::delete('/{slug}/versions/{version}/delete', 'VersionController@destroy')->name('versions.destroy');
    Route::get('/{slug}/versions/{version}/download', 'VersionController@downloadVersion')->name('versions.download');
    Route::resource('/plugins', 'PluginController');
});

app/Models/Plugin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Plugin extends Model
{
    //
    protected $table = 'plugins';

    protected $fillable = ['slug', 'plugin_name', 'downloaded', 'description'];


    public function latestVersion()
    {
        return $this->hasOne('App\Models\Version', 'plugin_id', 'id')->latest();
    }
    public function versions()
    {
        return $this->hasMany('App\Models\Version', 'plugin_id', 'id')->latest();
    }
    public function banner() 
    {
        return $this->hasOne('App\Models\Images', 'plugin_id', 'id')->where('type', '=', 'banner');
    }

    public function screenshots() 
    {
        return $this->hasMany('App\Models\Images', 'plugin_id', 'id')->where('type', '=', 'Screenshot');
    }
}

app/Http/Controllers/PluginController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plugin;
use Illuminate\Http\Request;

class PluginController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $plugins = Plugin::all();
        return view('plugin.index', compact('plugins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('plugin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'plugin_name' => 'required|unique:plugins|max:255',
            'slug' => 'required|unique:plugins',
            'description' => 'required',
        ]);
        $plugin = new Plugin;
        $plugin->slug = $request->slug;
        $plugin->plugin_name = $request->plugin_name;
        $plugin->downloaded = 0;
        $plugin->description = $request->description;
        $plugin->save();
        return redirect()->route('plugins.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $plugin = Plugin::find($id)->with('banner')->first();
        if (!empty($plugin->banner)) {
            $slug = $plugin->banner->slug;
            $link = url("/image/$slug");
        }
        return view('plugin.edit', compact('plugin', 'link'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $plugin = Plugin::find($id);
        $request->validate([
            'plugin_name' => 'required|max:255',
            'slug' => 'required|unique:plugins,slug,' . $plugin->slug . ',slug',
            'description' => 'required',
        ]);

        $path = storage_path('app/public/' . $plugin->slug);
        $newPath = storage_path('app/public/' . $request->slug);
        $success = \File::moveDirectory($path, $newPath);

        $plugin->slug = $request->slug;
        $plugin->plugin_name = $request->plugin_name;
        $plugin->description = $request->description;
        $plugin->save();

        return redirect()->route('plugins.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $plugin = Plugin::find($id);
        $path = storage_path('app/public/' . $plugin->slug);
        \File::deleteDirectory($path);
        $plugin->delete();
        return redirect()->back();
    }
}

resources/views/plugin/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create a new plugin</div>

                <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error) 
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="post" action="{{ route('plugins.store') }}">
                    @csrf
                    <div class="form-group">
                        <label>Plugin name</label>
                        <input type="text" class="form-control" name="plugin_name" aria-describedby="pluginHelp" placeholder="Enter plugin" required>
                        <small id="pluginHelp" class="form-text text-muted">Enter a name for your plugin (this will be visable on the wordpress dashboard)</small>
                    </div>
                    <div class="form-group">
                        <label>Slug name</label>
                        <input type="text" class="form-control" name="slug" aria-describedby="slugHelp" placeholder="Enter slug" required>
                        <small id="slugHelp" class="form-text text-muted">Note: The slugname will be used inside the update link (http://example.com/$slugname/update).</small>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" aria-describedby="descriptionHelp" required></textarea>
                        <small id="descriptionHelp" class="form-text text-muted">The description will be visable for wordpress users.</small>
                    </div>
                    <button type="submit" class="btn btn-primary">Create plugin</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/plugin/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit a plugin
                     <ul class="nav nav-tabs card-header-tabs pull-right"  id="myTab" role="tablist">
                        <li class="nav-item">
                        <a class="nav-link active" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="true">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="banner-tab" data-toggle="tab" href="#banner" role="tab" aria-controls="banner" aria-selected="false">Banner</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="screenshots-tab" data-toggle="tab" href="#screenshots" role="tab" aria-controls="screenshots" aria-selected="false">Screenshots</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error) 
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="settings" role="tabpanel" aria-labelledby="settings-tab">
                        {!! Form::model($plugin, ['route' => ['plugins.update', $plugin->id]]) !!}
                        {{ method_field('PATCH') }}
                        @csrf
                        <div class="form-group">
                            <label>Plugin name</label>
                            {{ Form::text('plugin_name', $plugin->plugin_name, ['class' => 'form-control','required' => 'required']) }}
                            <small id="pluginHelp" class="form-text text-muted">Enter a name for your plugin (this will be visable on the wordpress dashboard)</small>
                        </div>
                        <div class="form-group">
                            <label>Slug name</label>
                            {{ Form::text('slug', $plugin->slug, ['class' => 'form-control', 'required' => 'required']) }}
                            <small id="slugHelp" class="form-text text-muted">Note: The slugname will be used inside the update link (http://example.com/$slugname/update).</small>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            {{ Form::textarea('description', $plugin->description, ['class' => 'form-control', 'required' => 'required']) }}
                            <small id="descriptionHelp" class="form-text text-muted">The description will be visable for wordpress users.</small>
                        </div>
                        <button type="submit" class="btn btn-primary">update plugin</button>
                        {!! Form::close() !!}
                    </div>
                    <div class="tab-pane fade" id="banner" role="tabpanel" aria-labelledby="banner-tab">
                        @if(!empty($link))
                        <div class="container" style="height:500px;">
                            <img src="{{ $link }}" style='max-width: 100%; max-height: 100%;'>
                        </div>
                        @endif
                        <file-upload :plugin="{{ $plugin->id }}"></file-upload>
                    </div>
                    <div class="tab-pane fade" id="screenshots" role="tabpanel" aria-labelledby="screenshots-tab">
                        <screenshot-manager plugin="{{ $plugin->slug }}"></screenshot-manager>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/plugin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Plugins <a href="{{ route('plugins.create')}}"> <input class="btn btn-primary" style="float:right;" value="Create a new plugin"></a></div>

                <div class="card-body">
                <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>name</th>
                        <th>slug</th>
                        <th class="text-right">Action</th>
                    </tr>
                </thead>
                @foreach($plugins as $plugin)
                    <tr>
                        <td>{{ $plugin->id }}</td>
                        <td>{{ $plugin->plugin_name }}</td>
                        <td>{{ $plugin->slug }}</td>
                        <td class="text-right">
                            <a class='btn btn-secondary btn-xs' href="{!! route('versions.index', ['slug' => $plugin->slug]) !!}"><span class="glyphicon glyphicon-edit"></span> versions</a> 
                            <a class='btn btn-info btn-xs' href="{!! route('plugins.edit', [$plugin->id]) !!}"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                            {{ Form::open(['route' => ['plugins.destroy', $plugin->id], 'method' => 'post', 'style' => 'display:inline']) }}
                            {{ csrf_field() }}
                             {{ method_field('DELETE') }}
                             <input type="submit" class="btn btn-danger btn-xs" value="Del">
                            {{ Form::close() }}
                    </tr>
                @endforeach
                 </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection